import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Mini-Fundme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Mini FundMe!
        </h1>

        <p className={styles.description}>
          Mini Fundme is online fundraising platform which you can discover various fundraiser <br/> and create your own fundraiser in just a few minute.
        </p>

        <div className={styles.grid}>
          <a onClick={() => router.push("/fundme")} className={styles.card}>
            <h2>Discover &rarr;</h2>
            <p>Find fundraiser and their story which you may interest and make a donation.</p>
          </a>

          <a onClick={() => router.push("/fundme/create")} className={styles.card}>
            <h2>Create fundraiser&rarr;</h2>
            <p>Start your Fundraiser which you can tell your story and raise money</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
